version: '3.4'

services:
  odoo:
    image: pascal90/duzapaczka
    build: .
    ports:
      - "80:8069"
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8069"]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 15s
    deploy:
      update_config:
        order: start-first

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
